# Generated by Django 5.0.2 on 2024-02-17 01:16

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                choices=apps.authentication.models.get_countries,
                default="Canada",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female"), ("O", "other")],
                default="M",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
